# Setup
title:               Arjun Surendran
url:                 arjunsurendran.dev
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Arjun Surendran
  email:             arjunsurendr@gmail.com

# Gems
plugins:
  - jekyll-paginate

